import About from "@/components/About";
import ContactUs from "@/components/ContactUs";

import Hero from "@/components/Hero";
import Navbar from "@/components/Navbar";
import Skills from "@/components/Skills";
import Head from "next/head";

export default function Home() {
	return (
		<>
			<Head>
				<title>Harsha</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Navbar />
			<Hero />
			<About />
			<Skills />
			<ContactUs />
		</>
	);
}
